name: "Keep Takin' The Med"
favicon: null
layout_spectrum: 0.99501
typography_spectrum: 0.24003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#677724'
    - '#000000'
    - '#ff0000'
    - '#fdfdfd'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
