name: "Keep Takin' The Med"
favicon: null
layout_spectrum: 0.49369333824142814
typography_spectrum: 0.08229817147366703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8346990388818085
  lightness: 0.2453186851926148
  saturation: 0.8838067436590791
  rhythmicContrast: 0.8247533394023776
purpose: []
